1.8.9
teaconmc/xibao pull request #3
Opened 2022-10-15 15:57 UTC by keaidehuangpi

这是一件如此简单的事可是你们却不愿意做
把它转到1.8.9

2022-10-15 17:51 UTC, 3TUSK commented
首先，你有没有注意到，你的目标分支的名字里写着 `1.18-forge`。

------

> 可是你们却不愿意做

因为这个 Mod 最初是为 TeaCon 2022 准备的。TeaCon 2022 使用 1.18.2，所以我们也只准备了 1.18.2。

------

不过为啥是 1.8.9？

2022-10-16 01:31 UTC, keaidehuangpi commented
首先，我确实推的是1.8.9。
如果推错了那么我是笨比

2022-10-16 01:32 UTC, keaidehuangpi commented
你们mod的评论区那么多人力呼吁要189版本你们视而不见么？

2022-10-16 04:03 UTC, 3TUSK commented
> 首先，我确实推的是1.8.9。

对，但是目标分支叫 `1.18-forge`。我觉得让一个名字是 `1.18-forge` 的分支里有一个目标游戏版本是 1.8.9 的 Mod 颇有误导他人的嫌疑。

当然，GitHub 允许你切换 Pull Request 的目标分支，所以这个问题其实也不是那么难以解决，但在这个之前还有一些问题需要解决，请往下读。

> 你们mod的评论区那么多人呼吁要189版本你们视而不见么？

首先，我们的时间和精力有限，不可能什么地方的评论每天都翻一遍，这一点还希望能多多理解。

我假定你在说的是 MCMOD 百科的评论区。我刚刚去翻了一下，确实有评论表达了「想要适用于 1.8[.9] 的版本」的想法，但和总评论数相比，占比并不高。不过这不重要。重要的是「多维护一个版本的必要条件」。

TeaCon 执行委员会的成员大都是学生，有一小部分成员已经参加工作，每天首先要考虑的是学业或者事业，等到有空闲时间时才能来打理 TeaCon。因此，我们能花在维护 TeaCon 基础设施的 Mod 上的时间并不多。到目前为止我们也没有 backport 新版 TeaCon 基础设施的 Mod 的特性到旧版游戏上（特指 SlideShow 和 AreaControl），对于今年未使用的 Mod（Nickname、SimplePermission）我们也没有迁移到新版。都是因为时间和精力有限。
实际上今年 TeaCon 2022 的最终版整合包、地图等的发布就稍稍有点「延迟」：虽然我们在展示服务器关闭后就打包上传了整合包、地图等，但下载链接却因为负责网站前端的几位开发者现实中忙不开而没能及时更新到网站上，直到昨天才搞定。

维护一个适用于 Minecraft 1.8.9 的《喜报》Mod 从技术角度来说并不难，但这里面有一些细节问题要解决：

  1. 基于 ForgeGradle 2.1 的项目还能正常构建吗？不知道 @ZekerZhayard 能不能帮忙回答一下。
  2. 如果我们开了这个先例，那是不是意味着，如果有人问 1.7.10、1.10.2、1.11.2、1.12.2、1.14.4、1.15.2、1.16.5、…… 之类的版本，我们也应该提供支持？其他的 TeaCon 基础设施 Mod 是不是也应该有一样的待遇？谁来负责维护呢？虽然这个 Mod 很小，但看上去有人认为这个 Mod 的功能还可以再多一些，是不是也应该把这些人的建议都实现一遍……？

说这么多想表达的意思只有一个：我们的时间和精力是有限的。不然我们早就每个版本、每个加载器都来一遍了，TeaCon 也就可以有 Fabric 赛道了。

或者也可以开放社区贡献者参与。等等，现在就是开放的（见 SignMeUp、SlideShow）。但总得有人来复核每一个 Pull Request，总不能看都不看直接点“Merge pull request”吧。

------

在我们今年 TeaCon 2022 的复盘文档里有一条「考虑对外正式发布一部分 Mod」，多少和这个问题有些联系。希望能有所进展吧。要做的事情***还有很多***呢。

2022-10-16 04:15 UTC, 3TUSK requested changes
简单过了一遍你的 PR。

不知道为什么你又复制了一份 `xibao.png` 在 `src/main/resources` 下。Minecraft 识别不到这个的。

2022-10-16 04:15 UTC, 3TUSK commented on .github/workflows/release.yml
> -name: release
这是我们基于 GitHub Action 的持续集成（Continuous Integration）脚本，负责自动构建并发布新版。

我不太确定非默认分支上的 GitHub Action 还能不能运行，得确认一下。但直接删掉肯定是不对的。

2022-10-16 04:15 UTC, 3TUSK commented on build.gradle
> -jar.finalizedBy('reobfJar')
`publishing` 块和自动构建及发布有关，原则上并不能一删了之。

下面的 `task("githubActionOutput")` 同理。

2022-10-16 04:15 UTC, 3TUSK commented on src/main/java/org/teacon/xibao/Xibao.java
> +        if (e.gui instanceof GuiDisconnected){
没有检查游戏目录下是否存在 `.xibao_stop`。

当这个文件存在时（无视其内容），不应该绘制喜报图片。

与这个功能相对应的「不再显示喜报」按钮也没了。

2022-10-16 04:15 UTC, 3TUSK commented on src/main/resources/mcmod.info
> +  "modid": "examplemod",
整个 `mcmod.info` 都是 MDK 自带的版本，没有按实际情况修改。

2022-10-16 04:15 UTC, 3TUSK commented on gradlew
> -#!/bin/sh
`gradlew` 的权限需要保持 `100755` 以确保在 Linux、macOS 上可执行（`chmod +x`）。

2022-10-16 04:15 UTC, 3TUSK commented on src/main/java/org/teacon/xibao/Xibao.java
> +@Mod(modid = Xibao.MODID, version = Xibao.VERSION)
@ZekerZhayard 我记得 1.8.9 还没有 `clientSideOnly = true`，那如果我想确保这个 Mod 是 client-only 的应该怎么做？

2022-10-16 04:22 UTC, ZekerZhayard commented
> 基于 ForgeGradle 2.1 的项目还能正常构建吗？不知道 @ZekerZhayard 能不能帮忙回答一下。
可以构建，但是想在最新版的 IDEA 上正常开发需要做一些小修改，比如 Gradle 版本、IDEA 构建输出目录、FG 的 genIntellijRuns 的输出等

2022-10-16 04:25 UTC, ZekerZhayard commented on src/main/java/org/teacon/xibao/Xibao.java
> +@Mod(modid = Xibao.MODID, version = Xibao.VERSION)
https://github.com/MinecraftForge/MinecraftForge/blob/1.8.9/src/main/java/net/minecraftforge/fml/common/Mod.java#L96

2022-10-16 04:36 UTC, ZekerZhayard commented on src/main/java/org/teacon/xibao/Xibao.java
> +    public static final String MODID = "examplemod";
为什么 modid 是 examplemod

2022-10-16 04:38 UTC, Neubulae commented
您好，您愿意做，您来：）

2022-10-16 05:36 UTC, keaidehuangpi commented
关于你们对我作的更改的疑问，我的回答是我没有使用你们的构建脚本，而是重新下载了mdk。
xibao.png复制纯属手贱。
至于维护问题，我现在不就在社区维护么？你们加的那些功能其实不必有，其他版本的mod只需要显示喜报就可以了。

2022-10-16 08:11 UTC, ZekerZhayard commented
https://github.com/keaidehuangpi/xibao/pull/1

2022-10-16 08:30 UTC, Neubulae commented
您愿意做，您这不就来了么：）

2022-10-16 10:17 UTC, SeraphJACK commented
> 这是一件如此简单的事可是你们却不愿意做
> 把它转到1.8.9

这个 Mod 本身就是为了 TeaCon 2022 写的，我们从来没有在 TeaCon 以外的平台正式发布过，也没有承诺过会长期维护它。

> 首先，我确实推的是1.8.9。
> 如果推错了那么我是笨比

你发送的 PR 的目标分支是 1.18 。

> 你们mod的评论区那么多人呼吁要189版本你们视而不见么？

见上，我们从来没有在任何地方发布过此 mod ，也不知道你说的评论区是哪里。我们也没有义务一定要履行别人的“呼吁”。

> 至于维护问题，我现在不就在社区维护么？你们加的那些功能其实不必有，其他版本的mod只需要显示喜报就可以了。

如果你不认同我们所要求的 Guidlines ，你可以选择不发 PR 。这个 Mod 是 Unlincese 的，你可以随意修改之后再发布。

2022-10-16 13:42 UTC, keaidehuangpi commented
好吧,mcmod.cn确实有你们的mod。
那么我选择关闭pr。不，我并不是在谴责你们，只是吐槽一下而已
--对不起给你们造成困扰

2022-10-16 13:42 UTC, closed without merging